### ISSUE TITLE
Initial configuration file not parseable

### ISSUE THREAD

**Issue by ennui93** [pablo33/Shotwell-event2folder#11]
Initial configuration file is created with tab indentations, which makes the file unparseable when attempting import.

```
$ python3 Shotwell_event2folder.py 
Shotwell_event2folder.py:5: PyGIWarning: GExiv2 was imported without specifying a version first. Use gi.require_version('GExiv2', '0.10') before import to ensure that the right version gets loaded.
  from gi.repository import GExiv2
Loading user configuration....
Traceback (most recent call last):
  File "Shotwell_event2folder.py", line 217, in <module>
    import Shotevent2folder_cfg
  File "/home/user/.Shotwell-event2folder/Shotevent2folder_cfg.py", line 6
    librarymainpath = "/home/user/Pictures"
    ^
IndentationError: unexpected indent
```

Editing the configuration file and removing the indentation rectifies the issue.

**Comment by pablo33** [comment]
I revised code that generates de initial config file, deleted all the tabs to ensure a good parsing.

Thanks very much for the issue.
