### ISSUE TITLE
mess with int and string on mintepoch

### ISSUE THREAD

**Issue by pablo33** [pablo33/Shotwell-event2folder#21]
error encountered on runtime:

> Traceback (most recent call last):
>   File "Shotwell_event2folder.py", line 911, in <module>
>     TimeOriginalEpoch, decideflag = mediainfo (Filepath, assignstat)
>   File "Shotwell_event2folder.py", line 557, in mediainfo
>     if mintepoch < yearfound < '2038':
> TypeError: '<' not supported between instances of 'int' and 'str'

mintepoch needs to be a string

**Comment by pablo33** [comment]
Fixed.
